spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/bookservice #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver
#     url : jdbc:mysql://localhost:3306/bookservice
#     username : root
#     password : root
#     driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true #띄어쓰기 8칸

#logging.level: #띄어쓰기 없음
#  org.hibernate.SQL: debug #띄어쓰기 2칸

server:
  servlet:
    session:
      tracking-modes: cookie